### PR TITLE
Use PG 10.4 to align w/ actual environments

### PR DESCRIPTION
**Pull request by mcritchlow**
@ucsdlib/developers - Just FYI I'm getting this staged up. We should probably wait until https://github.com/ucsdlib/damspas/pull/496 is merged (maybe today?) and @jgorney has updated Test/Staging as well to get a few more eyes on it.

### CODE REVIEW

**Comment by lsitu** [comment]
@mcritchlow Should this be tested after it's merged?

**Comment by mcritchlow** [comment]
@lsitu - Yeah, definitely. My plan is to manually trigger a CircleCI build once we decide 10.4 seems to work well in Test/Staging. If anything odd happens we can troubleshoot, or even revert, from there.

**Comment by lsitu** [comment]
👍

**Comment by hweng** [comment]
:+1:

**Comment by VivianChu** [comment]
👍

**Pull request merged**
